// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZjMGgQ5mUuwtDkcnAnXYlnP_wSiJRhVo',
    appId: '1:1059997539785:web:418e1cfdb07cbd5206dc18',
    messagingSenderId: '1059997539785',
    projectId: 'ecommerceapp-f7fe6',
    authDomain: 'ecommerceapp-f7fe6.firebaseapp.com',
    storageBucket: 'ecommerceapp-f7fe6.firebasestorage.app',
    measurementId: 'G-K765M4DQB8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCbc0Ree7n3hMrVUSAlEk4PclyPOCOzOg',
    appId: '1:1059997539785:android:422888fb86aeb19806dc18',
    messagingSenderId: '1059997539785',
    projectId: 'ecommerceapp-f7fe6',
    storageBucket: 'ecommerceapp-f7fe6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATcIPDNcmBn5XXxFgNmENgwmwf6RqHLEY',
    appId: '1:1059997539785:ios:c123f4e063e81b0806dc18',
    messagingSenderId: '1059997539785',
    projectId: 'ecommerceapp-f7fe6',
    storageBucket: 'ecommerceapp-f7fe6.firebasestorage.app',
    iosBundleId: 'com.example.product',
  );
}
